# Generated by Django 4.1 on 2025-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreactor', models.CharField(max_length=100)),
                ('imagenactor', models.ImageField(null=True, upload_to='libreria/static/img', verbose_name='ImagenActor')),
                ('textoactor', models.TextField(blank=True, default='', null=True, verbose_name='TextoActor')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id_capitulo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('temporada', models.IntegerField(verbose_name='Temporada')),
                ('numero_temporada', models.IntegerField(verbose_name='Numero_de_temporada')),
                ('fecha', models.CharField(default='', max_length=10)),
                ('imdb', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('titulo_ingles', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('titulo_espaniol', models.CharField(max_length=100)),
                ('imagen_vertical', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Imagen_verticial')),
                ('imagen1_horizontal', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Imagen1_horizontal')),
                ('imagen2_horizontal', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Imagen2_horizontal')),
                ('visto', models.BooleanField(default=False, null=True, verbose_name='Vista')),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id_invitado', models.AutoField(primary_key=True, serialize=False)),
                ('id_capitulo', models.IntegerField(verbose_name='id_capitulo')),
                ('nombreinvitado', models.CharField(max_length=100)),
                ('imageninvitado', models.ImageField(null=True, upload_to='libreria/static/img', verbose_name='ImagenInvitado')),
                ('textoinvitado', models.TextField(blank=True, default='', null=True, verbose_name='TextoInvitado')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('id_capitulo', models.IntegerField(verbose_name='id_capitulo')),
                ('plot', models.TextField(blank=True, default='', null=True, verbose_name='Plot')),
                ('textoreview', models.TextField(blank=True, default='', null=True, verbose_name='Textoreview')),
            ],
        ),
    ]
