# Generated by Django 4.1 on 2025-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='titulo_espaniol',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='titulo_ingles',
            field=models.CharField(max_length=100),
        ),
    ]
