# Generated by Django 4.1 on 2025-05-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morse', '0005_alter_capitulo_imagen1_horizontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='imageninvitado',
            field=models.ImageField(null=True, upload_to='', verbose_name='ImagenInvitado'),
        ),
    ]
