# Generated by Django 4.1 on 2025-06-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morse', '0006_alter_invitado_imageninvitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='imagen1_horizontal',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen1_horizontal'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='imagen2_horizontal',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen2_horizontal'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='imagen_vertical',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen_vertical'),
        ),
    ]
